backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "menu" # Used in routes, e.g., /admin/collections/menu
    label: "Menu" # Used in the UI
    folder: "source/_posts/menu" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this menu
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "hidden", default: "menu"}
      - {label: "Order", name: "order", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  
  - name: "home" # Used in routes, e.g., /admin/collections/menu
    label: "Home" # Used in the UI
    folder: "source/_posts/home" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this menu
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "string", default: "homepage"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "markdown"}
      - {label: "Text Left", name: "textleft", widget: "markdown"}

  - name: "services" # Used in routes, e.g., /admin/collections/menu
    label: "Services" # Used in the UI
    folder: "source/_posts/services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this menu
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "string", default: "services"}
      - {label: "Icon", name: "icon", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "markdown"}
      - {label: "Text Long", name: "textlong", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", optional: true}
      
  - name: "pages" # Used in routes, e.g., /admin/collections/menu
    label: "Pages" # Used in the UI
    folder: "source/_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this menu
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "type", widget: "string", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "markdown"}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "source/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Language", name: "lang", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
